apiVersion: harbor-configuration.harbor.configuration/v1alpha1
kind: HarborConfiguration
metadata:
  name: harborconfiguration
spec:
  harborTarget:
    apiUrl: https://core.harbor.harbor-practice.co.uk/api/v2.0
    username: admin
    password: Harbor12345
  registry:
    name: quay
    type: quay
    targetRegistryUrl: https://quay.io
    description: Endpoint created via crd
  projectReq:
    projectName: quay-project
    storageLimit: -1
    public: true
  replication:
    name: quay-replication
    enablePolicy: true
    override: true
    filters:
    - type: name
      value: giantswarm/alpine
    trigger:
      type: manual