---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
- apiGroups:
  - administration.harbor.configuration
  resources:
  - harborconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - administration.harbor.configuration
  resources:
  - harborconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - administration.harbor.configuration
  resources:
  - harborconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - goharbor.io
  resources:
  - harborclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - harborclusters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - harborclusters/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
