---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - harbor-configuration.harbor.configuration
  resources:
  - harborconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor-configuration.harbor.configuration
  resources:
  - harborconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - harbor-configuration.harbor.configuration
  resources:
  - harborconfigurations/status
  verbs:
  - get
  - patch
  - update
