apiVersion: administration.harbor.configuration/v1alpha1
kind: HarborConfiguration
metadata:
  name: harborconfiguration
spec:
  harborTarget:
    name: harborcluster-sample
    namespace: harbor-cluster
    harborUsername: admin
  registry:
    name: quay
    provider: quay
    endpointUrl: https://quay.io
    description: Endpoint created via crd
  projectReq:
    projectName: quay-project
    storageQuota: -1
    public: true
  replication:
    name: quay-replication
    registryName: quay
    enablePolicy: true
    override: true
    destinationNamespace: quay-project
    filters:
      - type: name
        value: giantswarm/alpine
    triggerMode:
      type: manual
