{{- if .Values.crds.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harbor-config-operator.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "harbor-config-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "harbor-config-operator.crdInstall" . | quote }}
    {{- include "harbor-config-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "harbor-config-operator.CRDInstallSelector" . | quote }}
rules:
  - apiGroups:
      - ""
    resources:
      - jobs
    verbs:
      - create
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harbor-config-operator.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "harbor-config-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "harbor-config-operator.crdInstall" . | quote }}
    {{- include "harbor-config-operator.labels" . | nindent 4 }}
    role: {{ include "harbor-config-operator.CRDInstallSelector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harbor-config-operator.crdInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harbor-config-operator.crdInstall" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
