apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harbor-config.fullname" . }}-manager-role
  labels:
  {{- include "harbor-config.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
- apiGroups:
  - administration.harbor.configuration
  resources:
  - harborconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - administration.harbor.configuration
  resources:
  - harborconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - administration.harbor.configuration
  resources:
  - harborconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - goharbor.io
  resources:
  - harborclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - harborclusters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - harborclusters/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harbor-config.fullname" . }}-manager-rolebinding
  labels:
  {{- include "harbor-config.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "harbor-config.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "harbor-config.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
